backend:
  name: github
  repo: laurakcaron/laurakcaron.github.io
  branch: source

media_folder: src/images/
public_folder: images/

collections:
  - name: publication
    label: Publication
    folder: content/publications
    extension: json
    create: true
    slug: "{{date}}-{{filename}}"
    fields:
      - { name: filename, label: filename }
      - { name: date, label: Date, widget: select, options: ["2016", "2017", "2018", "2019", "2020", "2021", "2022"]}
      - { name: month, label: Month, widget: select, options: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]}
      - { name: shorttitle, label: Title }
      - { name: authors, label: Authors }
      - { name: place, label: Publisher, required: false}
      - { name: abstract, label: Abstract, widget: text, required: false}
      - { name: image, label: Image, widget: image, required: false}
      - { name: alt, label: Alt Text, widget: text, required: false}
      - { name: pubtype, label: Publication Type, widget: select, multiple: true, options: ["econ", "nonecon", "history", "journal", "blog", "institutional", "wp", "conference"], required: false}
      - { name: fulltextpdf, label: Full Text PDF, required: false}
      - { name: pubweb, label: Publisher Website, required: false}
  - name: resource
    label: Resource
    folder: content/resources
    extension: json
    create: true
    slug: "{{date}}-{{filename}}"
    fields:
      - { name: filename, label: filename }
      - { name: title, label: Title }
      - { name: link, label: Link }
      - { name: description, label: Description, widget: text, required: false}
      - { name: type, label: Resource Type, widget: select, multiple: true, options: ["student", "research", "accessibility"], required: false}
  - name: experience
    label: Experience
    folder: content/experiences
    extension: json
    create: true
    slug: "{{date}}-{{filename}}"
    fields:
      - { name: filename, label: filename }
      - { name: role, label: Role }
      - { name: company, label: Company }
      - { name: where, label: Location, widget: code }
      - { name: moreInfo, label: Description, widget: text, required: false}
  - name: mention
    label: Mentions
    folder: content/mentions
    extension: json
    create: true
    slug: "{{date}}-{{place}}"
    fields:
      - { name: filename, label: filename }
      - { name: date, label: Date, widget: select, options: ["2016", "2017", "2018", "2019", "2020", "2021", "2022"]}
      - { name: place, label: Publisher, required: false}
      - { name: shorttitle, label: Title }
      - { name: pubweb, label: Publisher Website, required: false}
      - { name: image, label: Image, widget: image, required: false}
      - { name: alt, label: Alt Text, widget: text, required: false}
      - { name: abstract, label: Abstract, widget: text, required: false}
