backend:
  name: github
  repo: laurakcaron/laurakcaron.github.io
  branch: source

media_folder: src/images/
public_folder: images/

collections:
  - name: publication
    label: Publication
    folder: publications
    extension: json
    create: true
    slug: "{{date}}-{{filename}}"
    fields:
      - { name: filename, label: filename }
      - { name: date, label: Date, widget: select, options: ["2016", "2017", "2018", "2019", "2020", "2021", "2022"]}
      - { name: month, label: Month, widget: select, options: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "December"]}
      - { name: shorttitle, label: Title }
      - { name: authors, label: Authors }
      - { name: place, label: Publisher, required: false}
      - { name: abstract, label: abstract, widget: text, required: false}
      - { name: image, label: Image, widget: image, required: false}
      - { name: alt, label: Alt Text, widget: text, required: false}
      - { name: pubtype, label: Publication Type, widget: select, multiple: true, options: ["econ", "nonecon", "journal", "blog"], required: false}
      - { name: fulltextpdf, label: Full Text PDF, required: false}
      - { name: pubweb, label: Publisher Website, required: false}